### ISSUE TITLE
很不错的组件，就是运行不起来

### ISSUE THREAD

**Issue by iq9891** [TaroXin/vue-pretty-logger#1]
![image](https://user-images.githubusercontent.com/5716990/39715055-884764d6-525e-11e8-9116-d1932bce7577.png)

环境
1. mac OS High Sierra 10.13.4
2. node -v 9.11.1
3. vue 2.3.4
4. webpack 2.7.0
5. vue-loader 12.2.2

**Comment by TaroXin** [comment]
能看看你的组件之中怎么写的吗？

**Comment by iq9891** [comment]
他看起来是 babel-polyfill 报错了。

```
// 我的入口文件
entry: {
    app: ['babel-polyfill', './src/main.js']
  },
```

**Comment by TaroXin** [comment]
问题已经修复了，升级最新版本就可以了，原因是 `.vue` 文件中没有写 `script` 标签导致的，我没有去加这个判断，现在已经加上了

**Comment by iq9891** [comment]
牛B啊，有时间试试，您这个插件解决了，线下调试的一些 log 输出问题，再次点赞

**Comment by iq9891** [comment]
已经验证，没毛病，问题已修复
