### ISSUE TITLE
与prettier基本无法兼容

### ISSUE THREAD

**Issue by ahjsrhj** [TaroXin/vue-pretty-logger#13]
尝试这个日志框架之后感觉挺好用的，但是与prettier 无法兼容，prettier会自动把形如
```
onClick() { // ${#}
},
```
的代码格式化为
```
 onClick() {
 // ${#}
},
```
并且好像没有配置项去更改这一行为（翻了文档，prettier可配置项很少，没有找到配置的地方）
这样打印方法参数就会变得很麻烦
有没有什么解决的办法？

**Comment by TaroXin** [comment]
暂时没有解决方案，如果`Prettier`无法提供不格式化注释的配置，那就没办法执行框架的调试行为

**Comment by ahjsrhj** [comment]
好的，感谢回复
