### ISSUE TITLE
The loader breaks, if the remark "// {#} -sign" is at the rear of the "await" statement.

### ISSUE THREAD

**Issue by stuartZhang** [TaroXin/vue-pretty-logger#3]
The below statement

> await download(url); // {#} -sign

doesn't output any of logs for the input variable "url" and the return value.

**Comment by TaroXin** [comment]
Thanks for you feedback.

`vue-pretty-logger` is still improving.

This feature will be added to the upcoming release.

**Comment by TaroXin** [comment]
This feature is currently available. The ` vue-pretty-logger` will treat the await statement as a function call. Please upgrade to version `0.8.7`.
