### ISSUE TITLE
有想法做一个 类似 Log wrapper 的 vs-code 插件吗

### ISSUE THREAD

**Issue by waynecz** [TaroXin/vue-pretty-logger#4]
这个 logger 超级棒！简直就是懒癌患者福音，在想有没有可能结合下我现在在用的 log-wrapper 的 vscode 插件，其实功能很简单，就是快捷键生成 `// {#}`  这一段注释（就是懒啦😛）

参考： [vs-code-log-wrapper](https://github.com/chrisvltn/vs-code-log-wrapper)

**Comment by TaroXin** [comment]
这个功能后续可以考虑加入，目前需要完善 vue-pretty-logger 的现有功能
