### ISSUE TITLE
不知道是不是BUG还是我自己项目的原因

### ISSUE THREAD

**Issue by yzw7489757** [TaroXin/vue-pretty-logger#5]
![image](https://user-images.githubusercontent.com/28922129/39753173-69e017f8-52f0-11e8-8e1f-ff4265b7004e.png)
在我项目里，除了-sign和-time能用之外，其他的要么是什么都不返回，要么就是打印hellowrold

**Comment by TaroXin** [comment]
`-count` 指令是有限制的，只能在方法声明时候使用，这个你应该仔细看一下配置问题
``` javascript
testFn (a, b) { // {#} -stop -count

}
```

`-t ` 指令是建立在 存在 `-e -d -w -i` 任意一个指令，如果没有这几个指令，`-t` 同样会失效

`-error` 指令是不存在的，请使用 `-e`

**Comment by yzw7489757** [comment]
假如vue组件内一个方法调用this.dataA  怎么能直接打印this.dataA的值。只能方法声明的时候才能用到话总觉得少了点什么，我想在方法内发出ajax之前时候去查看这个参数。

**Comment by TaroXin** [comment]
你可以如下使用
``` javascript
this.dataA() // {#}
// 这样会打印这个方法的返回值，但是不能打印方法的参数信息 
```
``` javascript
methods: {
    dataA (a, b) { // {#}
        // 这样会打印 a 和 b两个参数
    }
}
```
但是根据我的理解，你的需求是这样的
``` javascript
this.dataA(a) // {#}
// 你希望的结果是下面这样的
console.log(a)
const result = this.dataA(a)
console.log(result)
```

此功能目前还没有实现，不过是个好想法，下个版本更新会加上该功能，谢谢反馈

**Comment by yzw7489757** [comment]
还有一个问题，就是打印出来的值，行数会显示不对
![image](https://user-images.githubusercontent.com/28922129/39794799-caaa6532-537e-11e8-81e4-61d26caa1cc0.png)
![image](https://user-images.githubusercontent.com/28922129/39794828-ebc1d71e-537e-11e8-9356-803e44121893.png)
![image](https://user-images.githubusercontent.com/28922129/39795119-980119c6-5380-11e8-8e76-908ccd2a67e5.png)
![image](https://user-images.githubusercontent.com/28922129/39795131-a8e36870-5380-11e8-8863-482298c3a29a.png)

**Comment by TaroXin** [comment]
你点击后面的行数，他就会跳转到对应的地方，这个行数不是由 `vue-pretty-logger` 来对应的，是 `console` 的机制，行数也不一定会对应源文件中的行数，因为源文件会经过各种处理之后才会显示在页面上

**Comment by TaroXin** [comment]
需求功能已经实现，你可以使用 `-from` 参数对函数调用进行操作，该命令会打印方法调用时所传递的参数信息，`-sign` 参数存在的情况下则会输出函数实参所对应的形参
