### ISSUE TITLE
async 函数后加 // {#} 打包时候会报错

### ISSUE THREAD

**Issue by GarrenZhang** [TaroXin/vue-pretty-logger#7]
作者你好,无意中发现一个问题
在vue中写 async 函数, 例如
async test (a) {
}

**Comment by GarrenZhang** [comment]
作者你好,无意中发现一个问题
在vue中写 async 函数, 例如
async test (a) { // {#}

}
类似这样子的写法 在npm run build 的时候 会报错呢

**Comment by TaroXin** [comment]
可以贴一下报错的信息吗？

**Comment by GarrenZhang** [comment]
![qq 20180509130755](https://user-images.githubusercontent.com/29578076/39796708-c331e60c-538a-11e8-8ef5-6f91f9b348f9.png)
![84ua79 7x5c p kr9q v8x7](https://user-images.githubusercontent.com/29578076/39796798-4d66f7e0-538b-11e8-8a34-5b0ed23e6f68.png)
就是这个样子的 npm run build 的时候 会报错

**Comment by TaroXin** [comment]
这个应该不是 `vue-pretty-logger` 引起的错误，你是否删除掉 `// {#}` 后就能正常执行了呢？

`vue-pretty-logger` 会自动判断当前是否是开发环境的，在你运行 `npm run build` 的时候，`NODE_ENV is Product` 的情况下，`vue-pretty-logger` 是不会做处理的
